default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    adapter: sqlite3
    database: storage/development_admin.sqlite3
  sandbox:
    <<: *default
    adapter: sqlite3
    database: storage/development_sandbox.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

production:
  primary:
    adapter: postgresql
    encoding: unicode
    url: <%= ENV["ADMIN_DATABASE_URL"] %>
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  sandbox:
    <<: *default
    adapter: sqlite3
    database: storage/sandbox.sqlite3